/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObchodniPodminkyRouteImport } from './routes/obchodni-podminky'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as PlatbaRouteImport } from './routes/platba'
import { Route as EshopIndexRouteImport } from './routes/eshop/index'
import { Route as EshopSlugRouteImport } from './routes/eshop/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodniPodminkyRoute = ObchodniPodminkyRouteImport.update({
  id: '/obchodni-podminky',
  path: '/obchodni-podminky',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatbaRoute = PlatbaRouteImport.update({
  id: '/platba',
  path: '/platba',
  getParentRoute: () => rootRouteImport,
} as any)
const EshopIndexRoute = EshopIndexRouteImport.update({
  id: '/eshop/',
  path: '/eshop/',
  getParentRoute: () => rootRouteImport,
} as any)
const EshopSlugRoute = EshopSlugRouteImport.update({
  id: '/eshop/$slug',
  path: '/eshop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/platba': typeof PlatbaRoute
  '/eshop/$slug': typeof EshopSlugRoute
  '/eshop/': typeof EshopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/platba': typeof PlatbaRoute
  '/eshop/$slug': typeof EshopSlugRoute
  '/eshop': typeof EshopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obchodni-podminky': typeof ObchodniPodminkyRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/platba': typeof PlatbaRoute
  '/eshop/$slug': typeof EshopSlugRoute
  '/eshop/': typeof EshopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/platba'
    | '/eshop/$slug'
    | '/eshop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/platba'
    | '/eshop/$slug'
    | '/eshop'
  id:
    | '__root__'
    | '/'
    | '/obchodni-podminky'
    | '/ochrana-osobnich-udaju'
    | '/platba'
    | '/eshop/$slug'
    | '/eshop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObchodniPodminkyRoute: typeof ObchodniPodminkyRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  PlatbaRoute: typeof PlatbaRoute
  EshopSlugRoute: typeof EshopSlugRoute
  EshopIndexRoute: typeof EshopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodni-podminky': {
      id: '/obchodni-podminky'
      path: '/obchodni-podminky'
      fullPath: '/obchodni-podminky'
      preLoaderRoute: typeof ObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platba': {
      id: '/platba'
      path: '/platba'
      fullPath: '/platba'
      preLoaderRoute: typeof PlatbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eshop/': {
      id: '/eshop/'
      path: '/eshop'
      fullPath: '/eshop/'
      preLoaderRoute: typeof EshopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eshop/$slug': {
      id: '/eshop/$slug'
      path: '/eshop/$slug'
      fullPath: '/eshop/$slug'
      preLoaderRoute: typeof EshopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObchodniPodminkyRoute: ObchodniPodminkyRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  PlatbaRoute: PlatbaRoute,
  EshopSlugRoute: EshopSlugRoute,
  EshopIndexRoute: EshopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
